# Nombre: Sofía Pizarro

### Ejercicio 1.7 - Generando números binarios
Una función recursiva que genera e imprime todos los números binarios de ``n`` dígitos se puede plantear con un encabezado de la siguiente manera:

In [24]:
def genera_binarios(a,k,n):
    if k==n:
      print(a) # se generaron todos los digitos y se imprime el arreglo completo
    else:
      a[k]=0 # definimos el digito k como 0
      genera_binarios(a, k + 1, n) # llamamos recursivamente para ver combinaciones posibles con 0 en digito k
      a[k]=1 # definimos el digito k como 1
      genera_binarios(a, k + 1, n) # llamamos recursivamente para ver combinaciones posibles con 1 en digito k
      # como k va aumentando en 1, se van viendo los posibles arreglos con 1 y 0 en cada posicion a la derecha (k+1)
      # del digito fijado anteriormente, hasta que se llega al final del arreglo y se imprime

Donde ``a`` es un arreglo que contiene los unos y ceros de los números que se van generando, el cual se va rellenando con valores de izquierda a derecha, ``k`` es el grado de avance en el proceso de generación (más precisamente cuantos dígitos se han generado hasta esta llamada) y ``n`` es la cantidad total de dígitos que deben generarse (``n = len(a)``). Por lo tanto ``n-k`` es la cantidad de dígitos que faltan por generar. Esta función se llama la primera vez de la siguiente manera:

In [25]:
import numpy as np
a = np.empty(4,dtype=int)
genera_binarios(a,0,len(a))

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]


Este código debe generar la salida:

[0 0 0 0]

[0 0 0 1]

[0 0 1 0]

[0 0 1 1]

[0 1 0 0]

[0 1 0 1]

[0 1 1 0]

[0 1 1 1]

[1 0 0 0]

[1 0 0 1]

[1 0 1 0]

[1 0 1 1]

[1 1 0 0]

[1 1 0 1]

[1 1 1 0]

[1 1 1 1]

Se le pide que escriba las instrucciones de la función ``genera_binarios`` de acuerdo al siguiente algoritmo:

---



* si el valor de ``k`` es igual a ``n``, ya se han generado todos los dígitos por
    lo cual se imprime el arreglo en pantalla ``(print(a))``
    * si no, se hacen dos cosas:  
        - se pone un 0 en la ``k``-ésima posicion y se llama recursivamente
              a la función para que genere los dígitos restantes
                  - luego se pone un 1 en la misma ``k``-ésima posición (reemplazando el 0) y se
                        llama recursivamente a la función para que genere los dígitos restantes

                        Pruebe su función con para el caso ``n=4``. Asegúrese de que genere el mismo resultado que el que aparece en el enunciado.
                        